version: '2.6'
services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: denif
      MYSQL_DATABASE: test
      MYSQL_USER: denif
      MYSQL_PASSWORD: denif
    ports:
      - "3306:3306"
    volumes:
      - ./nasa-asteroid-api/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    restart: always

  nasa-asteroid-api-app:
      build: .
      environment:
        MYSQL_HOST: mysql-db
        MYSQL_PORT: 3306
        MYSQL_USER: denif
        MYSQL_PASSWORD: denif
      ports:
        - "8081:8081"
      depends_on:
        - mysql-db
      restart: always